### ISSUE TITLE
cocoapods use_frameworks! with Swift doesn't work

### ISSUE THREAD

**Issue by peantunes** [tombenner/nui#303]
Hi,
I'm trying to use NUI via Cocoapods using the use_frameworks to compile for Swift and it doesn't work.
It is showing an error: NUIParse.h file not found.
I checked there are more people with the same problem.

**Comment by peantunes** [comment]
I have created a fork with a fix for this problem, but I haven't tested using Objective-C or without use_frameworks! option. I can create a pull request if you need.
My suggestion is to have a branch specific for this case.

**Comment by desduvauchelle** [comment]
+1 What's the branch?

**Comment by peantunes** [comment]
https://github.com/peantunes/nui/tree/feature/support_to_swift_cocoapods_framework

**Comment by jurezove** [comment]
Still can't get it to work, even with that branch. :(

**Comment by timbodeit** [comment]
After using this myself for around 5 months, I filed a pull request for my [improve_framework_support](https://github.com/timbodeit/nui/tree/improve_framework_support) branch.
This should get rid of any `include of non-modular header inside framework module` errors.

If you're seeing something like `fatal error: 'SenTestingKit/SenTestingKit.h' file not found`, have a look at https://github.com/tombenner/NUIParse/pull/2

Using both [timbodeit/NUI:improve_framework_support](https://github.com/timbodeit/nui/tree/improve_framework_support) and [timbodeit/NUIParse:improve_cocoapods_framework_support](https://github.com/timbodeit/NUIParse/tree/improve_cocoapods_framework_support), I'm able to use NUI with cocoapods, using frameworks, importing them in Swift (using the native import syntax without a bridging header).

**Comment by Stunner** [comment]
@timbodeit Awesome man! Not a Swift user but I plan on merging your branch into [mine](https://github.com/Stunner/nui), which I plan on regularly maintaining. Could you please update the README to include all steps required in order to get the project working in a Swift project? That would be immensely helpful. Right now the instructions are the same as what is included in the original fork (not sure if that is correct or not).

**Comment by timbodeit** [comment]
@Stunner There really isn't anything special to do. All you have to do in your Swift file is to `import NUI`. Everything else is more or less the same as Objective-C.

I'm happy to update the Readme, but I would feel more comfortable doing that after both PRs have been merged. (If that is actually happening).

From looking at your branch: did you just not contribute back upstream or is `tombenner/NUI` not actively maintained anymore?

**Comment by Stunner** [comment]
@timbodeit I have two pull requests that have gone ignored. It appears (unfortunately) that this original fork of the project is highly inactive so I am taking it upon myself to maintain (and enhance) it for the time being. You can look at the [fork graph](https://github.com/tombenner/nui/network) and see that I have some history pulling in changes from other forks into mine.

If you update the README I can guarantee you I will merge it into my fork within a day. I believe that good documentation is what keeps projects going (even after they are abandoned [like this one]) so I do my best to keep it as up to date as possible. Additionally, since I am not actively working with Swift, I would like some place to point others to in case they have questions on how to go about it.

**Comment by timbodeit** [comment]
Ok, I had a look through last years pull request history.
Only a single PR has been merged within the last year. The rest didn't receive a single comment by any of the maintainers. Travis CI has been failing as far as the history goes back. My PR on NUIParse has been sitting for 5 Months without any input.
While I don't want to falsely accuse someone of abandoning their own project, I don't know what else to make of it.

@tombenner Please consider transferring the NUI project to an organization and adding motivated people such as @Stunner as maintainers. I haven't thoroughly checked the quality of the code on his fork, but on first sight it looks like he is doing pretty good work.
I find this sort of thing to be working pretty well for CocoaLumberjack. Author attribution in the Readme still goes to Robbie Hanson, but he is not very involved in the project anymore. Instead there are three other Maintainers currently managing the project.
IMHO that's a way better use for a project (and much better reference for the author), than slowly letting it die.

@Stunner It's nice to see that there is someone else actively working on NUI. However anybody developing a Pod that uses NUI can't rely on your fork as you can't specify sources in podspec files.
I would suggest cutting your fork loose from the upstream project, turning it into it's own repo and changing it's name. This would allow you to make releases and push them to the Cocoapods specs repo.
Please also duplicate NUIParse and have a look at the pull request.
Should you regularly be making releases of your fork, I'd be interested in further contributions

**Comment by Stunner** [comment]
> I would suggest cutting your fork loose from the upstream project, turning it into it's own repo and changing it's name. This would allow you to make releases and push them to the Cocoapods specs repo.

@timbodeit Interesting take, but I'm not too eager to do that unless my changes sufficiently deviate from NUI. I feel that doing that would potentially confuse people, especially if my changes are largely supplementary to the project, rather than a substitute. Your concerns over others not being able to easily utilize my project are valid and I think I can overcome that by specifying the exact [line to place in one's Podfile to reference my project](https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo) in my repo's README. Additionally, keeping my fork as a fork of NUI actually gets it more views as people look at the forks graph and see that my repo is most active and up-to-date which gets some people over to at least star it. But interesting suggestion nonetheless.

I'll take a look at NUIParse as well when I get a chance/have to make changes to the parsing engine (which I plan on doing in the long-term). Right now I am working on getting the custom override capabilities done with all styleable objects in NUI which is a long process to say the least. I would really like to hear your thoughts after reviewing my code for it, whenever you get the chance.

**Comment by timbodeit** [comment]
@Stunner My concerns were not about somebody not knowing how to reference your project in the Podfile.

Instead, it is about versioning. If you don't change the name, you can't push releases to the cocoapods specs repo. Without releases, you can't lock versions in your Podfile. And I normally don't just use the current master of any pod, unless the repo is my own, especially when it comes to App Store Releases.

The next part of the issue are *other* Pods. They don't have a Podfile (except for the Example Project). We are currently separating the different UI components of one of our Apps into multiple internal Pods. In the case of our Pod for common UI elements this dependency tree (of internal pods alone) goes three levels deep.  
It is theoretically possible to leave nui in those podspecs without a version specification and then specify some github source in every single Podfile that we have. Problem is my Pods won't lint if I do that. And I'm not going to turn the linter off for pushing them to our internal specs repo.

And on a side note: Your fork of nui currently won't lint either, even when including my changes. That's because of the problems in NUIParse. And you won't be able to tell the linter where to get that Pod from. The only way (without a private specs repo) is to fork NUIParse, rename it, release the renamed version to cocoapods, and using the new Pod in your NUI fork.

I do understand, that you might not care about those things and I'm not trying to pressure you into making changes to *your* repo if you don't want to do them.  
I'm simply saying, that for me personally your fork comes with too many limitations to be of any use. They would be solved by you regularly making releases.

I admit, you won't actually have to rename the git repo to do that. Though the name of the the Podfile does need to be different to do that. I usually don't expect a fork to be more actively maintained than the upstream project. That's the only reason why I suggested renaming the entire thing.

**Comment by Stunner** [comment]
@timbodeit Fair enough, thanks for taking the time to explain. I plan on tagging releases in my branch that can be linked to in the custom way, but it doesn't seem that would work for you. Could it be that this problem is a limitation of the linter rather than a problem with open source project workflow? Perhaps another issue much [like this](https://github.com/CocoaPods/CocoaPods/issues/2543) that hasn't been filed as yet?

From my experience working with open source projects, I know that maintainers typically spend time working on things they personally use. Considering your workflow appears to be far more complex than mine, and considering much of what you are doing with respect to CocoaPods goes over my head, I don't know if I can commit to doing what you recommend (primarily due to, as you mentioned, a lack of necessity for me).

What I think may work out (assuming of course this project remains inactive by the primary maintainers and other active maintainers aren't added) is you create a fork, merge in from active forks, and resubmit under a different name yourself as per your suggestions. I think that is the only realistic way to seamlessly move forward and to get around the problems you have brought to light. Additionally, you would be fixing this problem of yours for others as well. Also, you can add me and other actives as maintainers, thus just costing you some initial setup time.
